name: Solarpunk Soul's Blog
title: Solarpunk Soul
description: Perservering through global crises
github: [metadata]
markdown: kramdown
assets:
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
paginate: 5
paginate_path: "/blog/page/:num/"
future: true
